runtime: java17
env_variables:
  SPRING_PROFILES_ACTIVE: "gcp"
handlers:
- url: /.*
  script: this field is required, but ignored
manual_scaling: 
  instances: 1
entrypoint: java -Xmx128m -jar gcp-appengine-example-all.jar